chore: prepare for packaging tree-sitter parser releases

diff --git a/.github/workflows/build-macosx-x86_64.yml b/.github/workflows/build-macosx-x86_64.yml
--- a/.github/workflows/build-macosx-x86_64.yml
+++ b/.github/workflows/build-macosx-x86_64.yml
@@ -38,6 +38,10 @@ jobs:
           luaVersion: "5.1"
       - name: Install Luarocks
         uses: hishamhm/gh-actions-luarocks@master
+      - name: Configure architecture
+        run: |
+          mkdir -p /Users/runner/.luarocks
+          luarocks --verbose --local config arch macosx-x86_64
       - uses: rhysd/action-setup-vim@v1
         with:
           neovim: true
@@ -91,26 +95,23 @@ jobs:
         run: |
           luarocks --verbose --local --lua-version=5.1 install tree-sitter-norg-meta
           luarocks --verbose pack tree-sitter-norg-meta
-      # - name: Install `luarocks-build-treesitter-parser` Package
-      #   run: |
-      #     luarocks --verbose --local --lua-version=5.1 install luarocks-build-treesitter-parser
-      # - name: Get tree-sitter-parsers.json
-      #   uses: actions/checkout@v4
-      #   with: 
-      #     repository: nvim-neorocks/nurr
-      #     sparse-checkout: |
-      #       tree-sitter-parsers.json
-      #     path: nurr
-      # - name: Install tree-sitter parsers
-      #   run: |
-      #     # Filter out parsers that need their sources generated
-      #     # We might want to consider adding those too
-      #     langs=$(jq -r '.parsers[] | select((.install_info.requires_generate_from_grammar // false) == false) | .lang' nurr/tree-sitter-parsers.json)
-      #     for lang in $langs; do
-      #       rm "tree-sitter-$lang-scm-1.macosx-x86_64.rock" || true
-      #       luarocks --local --lua-version=5.1 install "tree-sitter-$lang" \
-      #         && luarocks pack "tree-sitter-$lang" || echo "Failed to pack tree-sitter-$lang"
-      #     done
+      - name: Get tree-sitter-parsers.json
+        uses: actions/checkout@v4
+        with: 
+          repository: nvim-neorocks/nurr
+          sparse-checkout: |
+            tree-sitter-parsers.json
+          path: nurr
+      - name: Install tree-sitter parsers
+        run: |
+          # Filter out parsers that need their sources generated
+          # We might want to consider adding those too
+          langs=$(jq -r '.parsers[] | select((.install_info.requires_generate_from_grammar // false) == false) | .lang' nurr/tree-sitter-parsers.json)
+          for lang in $langs; do
+            rm "tree-sitter-$lang-scm-1.macosx-aarch64.rock" || true
+            luarocks --local --lua-version=5.1 install "tree-sitter-$lang" \
+              && luarocks pack "tree-sitter-$lang" || echo "Failed to pack tree-sitter-$lang"
+          done
       - name: Regenerate Manifests and HTML
         run: luarocks-admin make-manifest --lua-version=5.1 .
       - name: commit-macosx-x86_64
