feat(linux): install dev tree-sitter-parser if release not found

diff --git a/.github/workflows/build-linux-x86_64.yml b/.github/workflows/build-linux-x86_64.yml
--- a/.github/workflows/build-linux-x86_64.yml
+++ b/.github/workflows/build-linux-x86_64.yml
@@ -61,8 +61,10 @@ jobs:
           # We might want to consider adding those too
           langs=$(jq -r '.parsers[] | select((.install_info.requires_generate_from_grammar // false) == false) | .lang' nurr/tree-sitter-parsers.json)
           for lang in $langs; do
+            rm "tree-sitter-$lang-scm-1.linux-x86_64.rock" || true
             luarocks --local --lua-version=5.1 install "tree-sitter-$lang" \
-              && luarocks pack "tree-sitter-$lang"
+              || luarocks --local --dev --lua-version=5.1 install "tree-sitter-$lang" \
+              && luarocks pack "tree-sitter-$lang" || echo "Failed to pack "tree-sitter-$lang"
           done
       - name: Regenerate Manifests and HTML
         run: luarocks-admin make-manifest --lua-version=5.1 .
