chore: merge branch 'main' of github.com:nvim-neorocks/rocks-binaries

diff --git a/.github/workflows/build-linux-x86_64.yml b/.github/workflows/build-linux-x86_64.yml
--- a/.github/workflows/build-linux-x86_64.yml
+++ b/.github/workflows/build-linux-x86_64.yml
@@ -64,7 +64,7 @@ jobs:
             rm "tree-sitter-$lang-scm-1.linux-x86_64.rock" || true
             luarocks --local --lua-version=5.1 install "tree-sitter-$lang" \
               || luarocks --local --dev --lua-version=5.1 install "tree-sitter-$lang" \
-              && luarocks pack "tree-sitter-$lang" || echo "Failed to pack "tree-sitter-$lang"
+              && luarocks pack "tree-sitter-$lang" || echo "Failed to pack tree-sitter-$lang"
           done
       - name: Regenerate Manifests and HTML
         run: luarocks-admin make-manifest --lua-version=5.1 .
